/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/piercings` | `/piercings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/joias` | `/joias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/artes` | `/artes`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/piercings` | `/piercings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/joias` | `/joias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/artes` | `/artes`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/piercings${`?${string}` | `#${string}` | ''}` | `/piercings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/joias${`?${string}` | `#${string}` | ''}` | `/joias${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/artes${`?${string}` | `#${string}` | ''}` | `/artes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/piercings` | `/piercings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/joias` | `/joias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/artes` | `/artes`; params?: Router.UnknownInputParams; };
    }
  }
}
